INSERT OR IGNORE INTO resources (name)
VALUES
    ('Ácido nítrico'),
    ('Ácido nítrico envasado'),
    ('Ácido sulfúrico'),
    ('Ácido sulfúrico envasado'),
    ('Agua'),
    ('Agua envasada'),
    ('Alambre'),
    ('Armazón modular'),
    ('Armazón modular fusionado'),
    ('Armazón modular pesado'),
    ('Azufre'),
    ('Barra de combustible de ficsonio'),
    ('Barra de combustible de plutonio'),
    ('Barra de combustible de uranio'),
    ('Barra de control electromagnética'),
    ('Barra de hierro'),
    ('Batería'),
    ('Bauxita'),
    ('Biocombustible líquido'),
    ('Biocombustible líquido envasado'),
    ('Biocombustible sólido'),
    ('Biomasa'),
    ('Bombona de fluidos vacía'),
    ('Cable'),
    ('Cableado automatizado'),
    ('Caliza'),
    ('Cápsula de ADN de alienígena'),
    ('Carbón'),
    ('Carbón compactado'),
    ('Carcasa de aluminio'),
    ('Caucho'),
    ('Célula de plutonio revestida'),
    ('Célula de singularidad'),
    ('Célula de uranio revestida'),
    ('Chatarra de aluminio'),
    ('Circuito impreso'),
    ('Cobre en polvo'),
    ('Cohete de propulsión térmica'),
    ('Combustible'),
    ('Combustible de cohete'),
    ('Combustible de cohete envasado'),
    ('Combustible envasado'),
    ('Combustible ionizado'),
    ('Combustible ionizado envasado'),
    ('Conector de alta velocidad'),
    ('Coque de petróleo'),
    ('Cristal de cuarzo'),
    ('Cristal de materia oscura'),
    ('Cronocristales'),
    ('Cuarzo bruto'),
    ('Cubo conversor de presiones'),
    ('Diamantes'),
    ('Disipador de calor'),
    ('Escultor bioquímico'),
    ('Esquirla de energía'),
    ('Estátor'),
    ('Estructura versátil'),
    ('Ficsonio'),
    ('Filtro de gas'),
    ('Filtro de yodo'),
    ('Fluctuador de MAR'),
    ('Gas nitrógeno'),
    ('Gas nitrógeno envasado'),
    ('Generador de campos magnéticos'),
    ('Gránulo de plutonio'),
    ('Hojas'),
    ('Hormigón'),
    ('Lámina de aluminio revestido'),
    ('Lámina de cobre'),
    ('Limitador de IA'),
    ('Lingote de acero'),
    ('Lingote de aluminio'),
    ('Lingote de caterio'),
    ('Lingote de cobre'),
    ('Lingote de ficsita'),
    ('Lingote de hierro'),
    ('Madera'),
    ('MAR'),
    ('MAR reanimada'),
    ('Materia fotónica excitada'),
    ('Matriz de energía alienígena'),
    ('Micelios'),
    ('Mineral de caterio'),
    ('Mineral de cobre'),
    ('Mineral de hierro'),
    ('Motor'),
    ('Motor modular'),
    ('Motor turbo'),
    ('Munición buscadora de rifle'),
    ('Munición de rifle'),
    ('Nobelisco'),
    ('Nobelisco de fragmentación'),
    ('Nobelisco de gas'),
    ('Nobelisco de pulso'),
    ('Nobelisco nuclear'),
    ('Ordenador'),
    ('Oscilador de cristal'),
    ('Oscilador de superposición'),
    ('Pasta nuclear'),
    ('Petróleo crudo'),
    ('Petróleo envasado'),
    ('Placas inteligentes'),
    ('Plancha de hierro'),
    ('Plancha de hierro reforzada'),
    ('Plástico'),
    ('Pólvora'),
    ('Pólvora sin humo'),
    ('Procesador neurocuántico'),
    ('Recipiente vacío'),
    ('Residuo de materia oscura'),
    ('Residuo de petróleo pesado'),
    ('Residuo de petróleo pesado envasado'),
    ('Residuos de plutonio'),
    ('Residuos de uranio'),
    ('Resina de polímero'),
    ('Rotor'),
    ('Servidor de expansión de IA'),
    ('Sílice'),
    ('Sílice disuelta'),
    ('Sistema de refrigeración'),
    ('Sistema director de montaje'),
    ('Solución de alúmina'),
    ('Solución de alúmina envasada'),
    ('Superordenador'),
    ('Tejido'),
    ('Tornillos'),
    ('Trígono de ficsita'),
    ('Tubería de acero'),
    ('Turboalambre'),
    ('Turbocombustible'),
    ('Turbocombustible envasado'),
    ('Turbomunición de rifle'),
    ('Unidad de control adaptativa'),
    ('Unidad de control por radio'),
    ('Unidad de deformación balística'),
    ('Uranio'),
    ('Uranio no fisible'),
    ('Varilla aturdidora'),
    ('Varilla de fragmentación'),
    ('Varilla de hierro'),
    ('Varilla explosiva'),
    ('Viga de acero'),
    ('Viga industrial reforzada');

INSERT OR IGNORE INTO machines (name)
VALUES
    ('Constructor'),
    ('Ensambladora'),
    ('Productor'),
    ('Envasadora'),
    ('Refinería'),
    ('Mezcladora'),
    ('Acelerador de partículas'),
    ('Transformador'),
    ('Codificador cuántico'),
    ('Horno'),
    ('Fundición'),
    ('Taladro Mk.1'),
    ('Taladro Mk.2'),
    ('Taladro Mk.3'),
    ('Extractor de agua'),
    ('Extractor de petróleo'),
    ('Extractor de pozo de recursos');

INSERT OR IGNORE INTO recipes (name)
VALUES
    ('Ácido nítrico'),
    ('Extraer ácido nítrico'),
    ('Ácido nítrico envasado'),
    ('Célula de uranio revestida'),
    ('Extraer ácido sulfúrico'),
    ('Ácido sulfúrico'),
    ('Alternativa: Sílice destilada'),
    ('Alternativa: Chatarra instantánea'),
    ('Alternativa: Electrodo de chatarra de aluminio'),
    ('Alternativa: Uranio fértil'),
    ('Uranio no fisible'),
    ('Batería'),
    ('Chatarra de aluminio'),
    ('Extraer agua'),
    ('Agua envasada'),
    ('Alternativa: Alambre de caterio'),
    ('Alternativa: Alambre de hierro'),
    ('Alternativa: Alambre fundido'),
    ('Alambre'),
    ('Alternativa: Armazón atornillado'),
    ('Alternativa: Armazón de acero'),
    ('Armazón modular'),
    ('Alternativa: Armazón termofusionado'),
    ('Armazón modular fusionado'),
    ('Alternativa: Armazón flexible pesado'),
    ('Alternativa: Armazón revestido pesado'),
    ('Armazón modular pesado'),
    ('Azufre (hierro)'),
    ('Azufre (carbón)'),
    ('Barra de combustible de ficsonio'),
    ('Alternativa: Unidad de combustible de plutonio'),
    ('Barra de combustible de plutonio'),
    ('Alternativa: Unidad de combustible de uranio'),
    ('Barra de combustible de uranio'),
    ('Alternativa: Barra de control electromagnética'),
    ('Barra de control electromagnética'),
    ('Alternativa: Barra de aluminio'),
    ('Alternativa: Barra de acero'),
    ('Barra de hierro'),
    ('Alternativa: Batería clásica'),
    ('Bauxita (cobre)'),
    ('Bauxita (caterio)'),
    ('Extraer biocombustible líquido'),
    ('Biocombustible líquido'),
    ('Biocombustible líquido envasado'),
    ('Biocombustible sólido'),
    ('Biomasa (micelios)'),
    ('Biomasa (hojas)'),
    ('Biomasa (madera)'),
    ('Extraer combustible ionizado'),
    ('Extraer combustible para cohetes'),
    ('Extraer gas nitrógeno'),
    ('Bombona de fluidos vacía'),
    ('Alternativa: Cable revestido'),
    ('Alternativa: Cable aislado'),
    ('Alternativa: Cable de turboalambre'),
    ('Cable'),
    ('Alternativa: Cableado automatizado de alta velocidad'),
    ('Cableado automatizado'),
    ('Caliza (azufre)'),
    ('Carbón (caliza)'),
    ('Carbón (hierro)'),
    ('Alternativa: Biocarbón'),
    ('Alternativa: Carbón vegetal'),
    ('Alternativa: Combustible de iones oscuros'),
    ('Combustible ionizado'),
    ('Alternativa: Combustible de cohetes nitro'),
    ('Alternativa: Carbón compactado'),
    ('Alternativa: Carcasa de aluminio revestido'),
    ('Carcasa de aluminio'),
    ('Alternativa: Caucho reciclado'),
    ('Caucho residual'),
    ('Caucho'),
    ('Alternativa: Célula de plutonio instantánea'),
    ('Célula de plutonio revestida'),
    ('Célula de singularidad'),
    ('Alternativa: Célula de uranio inyectado'),
    ('Alternativa: Circuito impreso de electrodos'),
    ('Alternativa: Circuito impreso de caterio'),
    ('Alternativa: Circuito impreso de silicio'),
    ('Circuito impreso'),
    ('Cobre en polvo'),
    ('Cohete de propulsión térmica'),
    ('Alternativa: Combustible diluido'),
    ('Extraer combustible'),
    ('Residuo de combustible'),
    ('Combustible'),
    ('Combustible de cohete'),
    ('Combustible de cohete envasado'),
    ('Alternativa: Combustible diluido envasado'),
    ('Combustible envasado'),
    ('Combustible ionizado envasado'),
    ('Alternativa: Conector de alta velocidad de silicio'),
    ('Conector de alta velocidad'),
    ('Coque de petróleo'),
    ('Alternativa: Cristal de cuarzo fundido'),
    ('Alternativa: Purificación de cuarzo'),
    ('Alternativa: Cristal de cuarzo puro'),
    ('Cristal de cuarzo'),
    ('Alternativa: Trampa de materia oscura'),
    ('Alternativa: Cristalización de materia oscura'),
    ('Cristal de materia oscura'),
    ('Cronocristales'),
    ('Cuarzo bruto (carbón)'),
    ('Cuarzo bruto (bauxita)'),
    ('Cubo de conversor de presiones'),
    ('Alternativa: Diamantes turbo'),
    ('Alternativa: Diamantes de petróleo'),
    ('Alternativa: Diamantes a base de petróleo'),
    ('Alternativa: Diamantes turbios'),
    ('Alternativa: Diamantes rosas'),
    ('Diamantes'),
    ('Alternativa: Intercambiador de calor'),
    ('Disipador de calor'),
    ('Escultor bioquímico'),
    ('Esquirla de energía sintética'),
    ('Alternativa: Estátor de turboalambre'),
    ('Estátor'),
    ('Alternativa: Estructura flexible'),
    ('Estructura versátil'),
    ('Ficsonio'),
    ('Filtro de gas'),
    ('Filtro de yodo'),
    ('Fluctuador de MAR'),
    ('Gas nitrógeno (caterio)'),
    ('Gas nitrógeno (bauxita)'),
    ('Gas nitrógeno envasado'),
    ('Generador de campos magnéticos'),
    ('Gránulo de plutonio'),
    ('Alternativa: Hormigón de calidad'),
    ('Alternativa: Hormigón mojado'),
    ('Alternativa: Hormigón de goma'),
    ('Hormigón'),
    ('Lámina de aluminio revestido'),
    ('Alternativa: Lámina de cobre vaporizada'),
    ('Lámina de cobre'),
    ('Alternativa: Limitador de IA de plástico'),
    ('Limitador de IA'),
    ('Alternativa: Lingote de acero de coque'),
    ('Alternativa: Lingote de acero sólido'),
    ('Alternativa: Lingote de acero compactado'),
    ('Lingote de acero'),
    ('Alternativa: Lingote de aluminio puro'),
    ('Lingote de aluminio'),
    ('Alternativa: Lingote de caterio puro'),
    ('Alternativa: Lingote de caterio templado'),
    ('Alternativa: Lingote de caterio lixiviado'),
    ('Lingote de caterio'),
    ('Alternativa: Lingote de cobre templado'),
    ('Alternativa: Lingote de cobre lixiviado'),
    ('Alternativa: Lingote de cobre puro'),
    ('Alternativa: Lingote de aleación de cobre'),
    ('Lingote de cobre'),
    ('Lingote de ficsita (caterio)'),
    ('Lingote de ficsita (aluminio)'),
    ('Lingote de ficsita (hierro)'),
    ('Alternativa: Lingote de hierro básico'),
    ('Alternativa: Lingote de hierro puro'),
    ('Alternativa: Lingote de hierro lixiviado'),
    ('Alternativa: Lingote de aleación de hierro'),
    ('Lingote de hierro'),
    ('MAR reanimada'),
    ('Materia fotónica excitada'),
    ('Matriz de energía alienígena'),
    ('Tejido'),
    ('Mineral de caterio (cuarzo)'),
    ('Mineral de caterio (cobre)'),
    ('Mineral de cobre (azufre)'),
    ('Mineral de cobre (cuarzo)'),
    ('Mineral de hierro (caliza)'),
    ('Alternativa: Motor eléctrico'),
    ('Alternativa: Motor robusto'),
    ('Motor'),
    ('Motor modular'),
    ('Alternativa: Motor turbo eléctrico'),
    ('Alternativa: Motor turbo presurizado'),
    ('Motor turbo'),
    ('Munición buscadora de rifle'),
    ('Munición de rifle'),
    ('Nobelisco'),
    ('Nobelisco de fragmentación'),
    ('Nobelisco de gas'),
    ('Nobelisco de pulso'),
    ('Nobelisco nuclear'),
    ('Alternativa: Ordenador de caterio'),
    ('Alternativa: Ordenador de cristal'),
    ('Ordenador'),
    ('Alternativa: Oscilador de cristal aislado'),
    ('Oscilador de cristal'),
    ('Oscilador de superposición'),
    ('Pasta nuclear'),
    ('Petróleo envasado'),
    ('Alternativa: Placas de plástico inteligente'),
    ('Placas inteligentes'),
    ('Alternativa: Plancha de acero fundido'),
    ('Alternativa: Plancha de hierro revestida'),
    ('Plancha de hierro'),
    ('Alternativa: Plancha de hierro adherida'),
    ('Alternativa: Plancha de hierro atornillada'),
    ('Alternativa: Plancha de hierro soldada'),
    ('Plancha de hierro reforzada'),
    ('Alternativa: Plástico reciclado'),
    ('Plástico residual'),
    ('Plástico'),
    ('Alternativa: Pólvora fina'),
    ('Pólvora'),
    ('Pólvora sin humo'),
    ('Procesador neurocuántico'),
    ('Alternativa: Recipiente de hierro revestido'),
    ('Alternativa: Recipiente de acero'),
    ('Extraer turbocombustible'),
    ('Extraer solución de alúmina'),
    ('Extraer residuo de petróleo pesado'),
    ('Extraer petróleo'),
    ('Recipiente vacío'),
    ('Servidor de expansión de IA'),
    ('Residuo de materia oscura'),
    ('Alternativa: Resina de polímero'),
    ('Alternativa: Residuo de petróleo pesado'),
    ('Residuo de petróleo pesado envasado'),
    ('Alternativa: Rotor de acero'),
    ('Alternativa: Rotor de cobre'),
    ('Rotor'),
    ('Alternativa: Sílice económico'),
    ('Solución de alúmina'),
    ('Sílice'),
    ('Alternativa: Dispositivo de refrigeración'),
    ('Sistema de refrigeración'),
    ('Sistema de director de montaje'),
    ('Alternativa: Alúmina chapucera'),
    ('Solución de alúmina envasada'),
    ('Alternativa: Ordenador de superestado'),
    ('Alternativa: Superordenador overclockeado'),
    ('Superordenador'),
    ('Alternativa: Tela de poliéster'),
    ('Alternativa: Tornillos fundidos'),
    ('Alternativa: Tornillos de acero'),
    ('Tornillos'),
    ('Trígono de ficsita'),
    ('Alternativa: Tubería de acero moldeado'),
    ('Alternativa: Tubería de hierro'),
    ('Tubería de acero'),
    ('Alternativa: Turboalambre fundido'),
    ('Turboalambre'),
    ('Alternativa: Turbocombustible mezclado'),
    ('Alternativa: Turbocombustible pesado'),
    ('Turbocombustible'),
    ('Turbocombustible envasado'),
    ('Turbomunición para rifle'),
    ('Unidad de control adaptativa'),
    ('Alternativa: Unidad de conexión de radio'),
    ('Alternativa: Sistema de control de radio'),
    ('Unidad de control por radio'),
    ('Unidad de deformación balística'),
    ('Mineral de uranio (bauxita)'),
    ('Varilla aturdidora'),
    ('Varilla de fragmentación'),
    ('Varilla de hierro'),
    ('Varilla explosiva'),
    ('Alternativa: Viga de aluminio'),
    ('Alternativa: Viga moldeada'),
    ('Viga de acero'),
    ('Alternativa: Tubería industrial reforzada'),
    ('Viga industrial reforzada'),
    ('Extracción de agua'),
    ('Extracción de bauxita'),
    ('Extracción de caliza'),
    ('Extracción de carbón'),
    ('Extracción de azufre'),
    ('Extracción de cuarzo bruto'),
    ('Extracción de MAR'),
    ('Extracción de caterio'),
    ('Extracción de cobre'),
    ('Extracción de hierro'),
    ('Extracción de petróleo crudo'),
    ('Extracción de uranio'),
    ('Extracción de gas nitrógeno');